services:
  - type: web
    name: travelx
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
